In [1]:
import pandas as pd

In [2]:
products = pd.read_csv("../data/raw/Skinpro - Skinpro (3).csv")

In [3]:
products.head()

,Skin type,Product,Concern,product_url,product_pic
0,Dry,Venusia Max Intensive Moisturizing Cream,"Acne,Hydration",https://dermatics.in/products/venusia-max-inte...,https://dermatics.in/cdn/shop/files/VENUSIA_4-...
1,"Oily,Combination",Saslic Foaming Face Wash,Whitehead/Blackhead,https://dermatics.in/products/cipla-saslic-foa...,https://dermatics.in/cdn/shop/files/saslic-foa...
2,Dry,The Derma Co 1% Hyaluronic Sunscreen Aqua Ultr...,Sun protection,https://amzn.to/464QBwM,https://m.media-amazon.com/images/I/51x3cj+-iU...
3,Dry,Hyalugel,Hydration,https://www.amazon.in/Hyalugel-Hyaluronic-Acid...,https://thebeautyinsideout.com/wp-content/uplo...
4,Normal,Himalaya Neem Face Wash,Pimples,https://himalayawellness.in/products/himalaya-...,https://himalayawellness.in/cdn/shop/files/100...

In [4]:
products.shape

(214, 5)

In [5]:
products.columns

Index(['Skin type', 'Product', 'Concern', 'product_url', 'product_pic'], dtype='str')

In [6]:
products.columns.tolist()

['Skin type', 'Product', 'Concern', 'product_url', 'product_pic']

In [7]:
products.dtypes

Skin type      str
Product        str
Concern        str
product_url    str
product_pic    str
dtype: object

In [8]:
products.isnull().sum()

Skin type      0
Product        0
Concern        0
product_url    1
product_pic    0
dtype: int64

In [9]:
products.duplicated().sum()

np.int64(0)

In [10]:
products['Skin type'].value_counts()

Skin type
Normal,Dry,Combination,Oily,Sensitive        51
Dry                                          27
Oily                                         23
Oily,Combination                             17
Sensitive                                    14
Normal                                       12
Combination                                   7
Dry,Normal                                    6
Normal,Dry,Combination                        5
Normal,Dry                                    5
Normal,Combination                            4
Dry,Sensitive                                 4
Sensitive,Oily                                3
Normal,Dry,Sensitive                          3
Oily,Dry                                      3
Dry                                           3
Dry,Oily,Normal,Combination,Sensitive         2
Normal,Oily                                   2
Sensitive,Combination                         2
Normal,Dry,Combination,Oily                   2
Normal, Oily, Sensitive, Dry, Combination     2
Normal,Oily,Dry                               2
Combination,Oily                              1
Normal,Combination,Oily,Dry,Sensitive         1
Dry,Sensitive,Combination                     1
Dry,Normal,Oily,Combination                   1
Oily,Sensitive,Combination                    1
Normal,Sensitive                              1
Dry,Combination                               1
Dry,Normal,Sensitive                          1
Dry,Combination,Oily,Sensitive                1
Dry, Sensitive, Combination                   1
Oily,Dry,Sensitive                            1
Oily                                          1
Dry,Normal,Combination                        1
Sensitive,Dry                                 1
Combination,Oily,Sensitive                    1
Name: count, dtype: int64

In [11]:
products['Concern'].value_counts()

Concern
Sun protection                         28
Hydration                              26
Acne                                   23
Pigmentation                           13
Broken barrier                         12
Skin soothing                           9
Pores                                   8
Exfoliation                             7
Hydration,Broken barrier                6
Pigmentation,Dark Spots                 6
Irritation                              5
Whitehead/Blackhead                     4
Pimples                                 4
Dark Spots                              4
Broken barrier,Hydration                4
Acne,Hydration                          3
Pores,Skin soothing                     3
Hydration,Skin soothing                 3
Hydration,Irritation                    2
Acne,Whitehead/Blackhead                2
Whitehead/Blackhead,Exfoliation         2
Acne,Dark Spots                         2
Whitehead/Blackhead,Acne                2
Whitehead/Blackhead,Pores               2
Irritation,Skin soothing                2
Pigmentation,Acne                       2
Skin soothing,Pores                     2
Exfoliation,Hydration                   2
Acne,Pores                              2
Pores,Dark Spots                        2
Hydration, Irritation                   1
Dark Spots,Pigmentation                 1
Hydration,Exfoliation                   1
Hydration,Broken barrier,Irritation     1
Sun protection,Broken barrier           1
Pimples,Acne                            1
Acne,Pimples                            1
 Acne                                   1
Sun protection,Hydration                1
Sun protection,Irritation               1
Acne,Whitehead/Blackhead,Pimples        1
Pores,Hydration                         1
Broken barrier,Whitehead/Blackhead      1
Exfoliation,Pigmentation                1
Hydration,Dark Spots                    1
Dark Spots,Hydration                    1
Pores,Exfoliation                       1
Pigmentation,Exfoliation                1
Hydration,Skin soothing,Irritation      1
Exfoliation,Whitehead/Blackhead         1
Pimples,Acne,Whitehead/Blackhead        1
Broken barrier, Hydration               1
Name: count, dtype: int64

In [12]:
products['Product'].nunique()

214

In [13]:
products.shape[0]

214

In [14]:
products.sample(5)

,Skin type,Product,Concern,product_url,product_pic
20,Dry,Rivela Tint Sunscreen Lotion SPF 50,Sun protection,https://www.clinikally.com/products/rivela-tin...,https://www.clinikally.com/cdn/shop/products/r...
109,Dry,La Pink White Haldi Face Toner with Kakadu Plum,Acne,https://www.myntra.com/toner/la+pink/la-pink-i...,https://rukminim2.flixcart.com/image/850/1000/...
105,"Normal,Dry,Combination,Oily,Sensitive",Plum 1% Oat & Allantoin Deep Nourish Face Wash,Broken barrier,https://plumgoodness.com/products/1-oat-allant...,https://m.media-amazon.com/images/I/61oB7c35Mt...
74,"Normal,Dry,Combination,Oily,Sensitive",Glambak Skin Glowing & Rejuvenating Face Wash,Exfoliation,https://www.amazon.in/Glambak-Skin-Glowing-Rej...,https://m.media-amazon.com/images/I/41N-esULkt...
76,"Normal,Dry,Combination,Oily",Foxtale Essentials Multivitamin Rose Mist & Toner,"Hydration,Broken barrier",https://www.nykaa.com/foxtale-essentials-multi...,https://m.media-amazon.com/images/I/71Ym59-Jfr...

In [15]:
products_clean = products.copy()

In [16]:
products_clean.columns = [
    'skin_type',
    'product',
    'concern',
    'product_url',
    'product_pic'
]

In [17]:
products_clean.columns

Index(['skin_type', 'product', 'concern', 'product_url', 'product_pic'], dtype='str')

In [18]:
products_clean.columns.tolist()

['skin_type', 'product', 'concern', 'product_url', 'product_pic']

In [19]:
products_clean[products_clean['product_url'].isnull()]

,skin_type,product,concern,product_url,product_pic
55,Dry,Earth Rhythm VITAMIN E INTENSE NOURISH DAY CREAM,Broken barrier,NaN,https://earthrhythm.com/cdn/shop/products/vitE...

In [20]:
products_clean['skin_type'].unique()

<StringArray>
[                                      'Dry',
                          'Oily,Combination',
                                    'Normal',
     'Dry,Oily,Normal,Combination,Sensitive',
                            'Sensitive,Oily',
                                      'Oily',
                          'Combination,Oily',
                                 'Sensitive',
                               'Combination',
                        'Normal,Combination',
     'Normal,Combination,Oily,Dry,Sensitive',
                 'Dry,Sensitive,Combination',
                               'Normal,Oily',
                      'Normal,Dry,Sensitive',
                                'Dry,Normal',
                                  'Oily,Dry',
                                      'Dry ',
                             'Dry,Sensitive',
               'Dry,Normal,Oily,Combination',
                    'Normal,Dry,Combination',
     'Normal,Dry,Combination,Oily,Sensitive',
                'Oily,Sensitive,Combination',
                     'Sensitive,Combination',
                          'Normal,Sensitive',
                                'Normal,Dry',
               'Normal,Dry,Combination,Oily',
 'Normal, Oily, Sensitive, Dry, Combination',
                           'Dry,Combination',
                      'Dry,Normal,Sensitive',
            'Dry,Combination,Oily,Sensitive',
               'Dry, Sensitive, Combination',
                        'Oily,Dry,Sensitive',
                           'Normal,Oily,Dry',
                                     'Oily ',
                    'Dry,Normal,Combination',
                             'Sensitive,Dry',
                'Combination,Oily,Sensitive']
Length: 37, dtype: str

In [21]:
products_clean['skin_type'].str.strip().unique()

<StringArray>
[                                      'Dry',
                          'Oily,Combination',
                                    'Normal',
     'Dry,Oily,Normal,Combination,Sensitive',
                            'Sensitive,Oily',
                                      'Oily',
                          'Combination,Oily',
                                 'Sensitive',
                               'Combination',
                        'Normal,Combination',
     'Normal,Combination,Oily,Dry,Sensitive',
                 'Dry,Sensitive,Combination',
                               'Normal,Oily',
                      'Normal,Dry,Sensitive',
                                'Dry,Normal',
                                  'Oily,Dry',
                             'Dry,Sensitive',
               'Dry,Normal,Oily,Combination',
                    'Normal,Dry,Combination',
     'Normal,Dry,Combination,Oily,Sensitive',
                'Oily,Sensitive,Combination',
                     'Sensitive,Combination',
                          'Normal,Sensitive',
                                'Normal,Dry',
               'Normal,Dry,Combination,Oily',
 'Normal, Oily, Sensitive, Dry, Combination',
                           'Dry,Combination',
                      'Dry,Normal,Sensitive',
            'Dry,Combination,Oily,Sensitive',
               'Dry, Sensitive, Combination',
                        'Oily,Dry,Sensitive',
                           'Normal,Oily,Dry',
                    'Dry,Normal,Combination',
                             'Sensitive,Dry',
                'Combination,Oily,Sensitive']
Length: 35, dtype: str

In [22]:
products_clean['skin_type'] = products_clean['skin_type'].str.strip()

In [23]:
products_clean['skin_type'].unique()

<StringArray>
[                                      'Dry',
                          'Oily,Combination',
                                    'Normal',
     'Dry,Oily,Normal,Combination,Sensitive',
                            'Sensitive,Oily',
                                      'Oily',
                          'Combination,Oily',
                                 'Sensitive',
                               'Combination',
                        'Normal,Combination',
     'Normal,Combination,Oily,Dry,Sensitive',
                 'Dry,Sensitive,Combination',
                               'Normal,Oily',
                      'Normal,Dry,Sensitive',
                                'Dry,Normal',
                                  'Oily,Dry',
                             'Dry,Sensitive',
               'Dry,Normal,Oily,Combination',
                    'Normal,Dry,Combination',
     'Normal,Dry,Combination,Oily,Sensitive',
                'Oily,Sensitive,Combination',
                     'Sensitive,Combination',
                          'Normal,Sensitive',
                                'Normal,Dry',
               'Normal,Dry,Combination,Oily',
 'Normal, Oily, Sensitive, Dry, Combination',
                           'Dry,Combination',
                      'Dry,Normal,Sensitive',
            'Dry,Combination,Oily,Sensitive',
               'Dry, Sensitive, Combination',
                        'Oily,Dry,Sensitive',
                           'Normal,Oily,Dry',
                    'Dry,Normal,Combination',
                             'Sensitive,Dry',
                'Combination,Oily,Sensitive']
Length: 35, dtype: str

In [24]:
skin_order = ['Normal', 'Dry', 'Oily', 'Combination', 'Sensitive']

def standardize_skin_type(value):
    types = [x.strip() for x in value.split(',')]
    types = sorted(types, key=skin_order.index)
    return ','.join(types)

In [25]:
standardize_skin_type('Oily,Combination')

'Oily,Combination'

In [26]:
standardize_skin_type('Combination,Oily')

'Oily,Combination'

In [27]:
standardize_skin_type('Normal,Dry,Combination,Oily,Sensitive')

'Normal,Dry,Oily,Combination,Sensitive'

In [28]:
products_clean['skin_type'] = products_clean['skin_type'].apply(standardize_skin_type)

In [29]:
products_clean['skin_type'].nunique()

24

In [30]:
products_clean['skin_type'].value_counts()

skin_type
Normal,Dry,Oily,Combination,Sensitive    56
Dry                                      30
Oily                                     24
Oily,Combination                         18
Sensitive                                14
Normal                                   12
Normal,Dry                               11
Combination                               7
Normal,Dry,Combination                    6
Dry,Sensitive                             5
Normal,Combination                        4
Normal,Dry,Sensitive                      4
Oily,Sensitive                            3
Dry,Oily                                  3
Normal,Dry,Oily,Combination               3
Dry,Combination,Sensitive                 2
Normal,Oily                               2
Oily,Combination,Sensitive                2
Combination,Sensitive                     2
Normal,Dry,Oily                           2
Normal,Sensitive                          1
Dry,Combination                           1
Dry,Oily,Combination,Sensitive            1
Dry,Oily,Sensitive                        1
Name: count, dtype: int64

In [31]:
products_clean['concern'].unique()

<StringArray>
[                     'Acne,Hydration',                 'Whitehead/Blackhead',
                      'Sun protection',                           'Hydration',
                             'Pimples',                        'Pigmentation',
                'Hydration,Irritation',               'Hydration, Irritation',
                                'Acne',            'Acne,Whitehead/Blackhead',
                          'Dark Spots',             'Dark Spots,Pigmentation',
            'Hydration,Broken barrier',               'Hydration,Exfoliation',
     'Whitehead/Blackhead,Exfoliation',                     'Acne,Dark Spots',
                      'Broken barrier', 'Hydration,Broken barrier,Irritation',
            'Whitehead/Blackhead,Acne',            'Broken barrier,Hydration',
                               'Pores',             'Pigmentation,Dark Spots',
       'Sun protection,Broken barrier',                         'Exfoliation',
                        'Pimples,Acne',           'Whitehead/Blackhead,Pores',
                        'Acne,Pimples',                              ' Acne ',
            'Irritation,Skin soothing',                   'Pigmentation,Acne',
            'Sun protection,Hydration',                          'Irritation',
                 'Skin soothing,Pores',                       'Skin soothing',
                 'Pores,Skin soothing',           'Sun protection,Irritation',
    'Acne,Whitehead/Blackhead,Pimples',               'Exfoliation,Hydration',
                     'Pores,Hydration',  'Broken barrier,Whitehead/Blackhead',
            'Exfoliation,Pigmentation',             'Hydration,Skin soothing',
                          'Acne,Pores',                'Hydration,Dark Spots',
                'Dark Spots,Hydration',                   'Pores,Exfoliation',
            'Pigmentation,Exfoliation',  'Hydration,Skin soothing,Irritation',
     'Exfoliation,Whitehead/Blackhead',    'Pimples,Acne,Whitehead/Blackhead',
                    'Pores,Dark Spots',           'Broken barrier, Hydration']
Length: 52, dtype: str

In [32]:
products_clean['concern'].unique()

<StringArray>
[                     'Acne,Hydration',                 'Whitehead/Blackhead',
                      'Sun protection',                           'Hydration',
                             'Pimples',                        'Pigmentation',
                'Hydration,Irritation',               'Hydration, Irritation',
                                'Acne',            'Acne,Whitehead/Blackhead',
                          'Dark Spots',             'Dark Spots,Pigmentation',
            'Hydration,Broken barrier',               'Hydration,Exfoliation',
     'Whitehead/Blackhead,Exfoliation',                     'Acne,Dark Spots',
                      'Broken barrier', 'Hydration,Broken barrier,Irritation',
            'Whitehead/Blackhead,Acne',            'Broken barrier,Hydration',
                               'Pores',             'Pigmentation,Dark Spots',
       'Sun protection,Broken barrier',                         'Exfoliation',
                        'Pimples,Acne',           'Whitehead/Blackhead,Pores',
                        'Acne,Pimples',                              ' Acne ',
            'Irritation,Skin soothing',                   'Pigmentation,Acne',
            'Sun protection,Hydration',                          'Irritation',
                 'Skin soothing,Pores',                       'Skin soothing',
                 'Pores,Skin soothing',           'Sun protection,Irritation',
    'Acne,Whitehead/Blackhead,Pimples',               'Exfoliation,Hydration',
                     'Pores,Hydration',  'Broken barrier,Whitehead/Blackhead',
            'Exfoliation,Pigmentation',             'Hydration,Skin soothing',
                          'Acne,Pores',                'Hydration,Dark Spots',
                'Dark Spots,Hydration',                   'Pores,Exfoliation',
            'Pigmentation,Exfoliation',  'Hydration,Skin soothing,Irritation',
     'Exfoliation,Whitehead/Blackhead',    'Pimples,Acne,Whitehead/Blackhead',
                    'Pores,Dark Spots',           'Broken barrier, Hydration']
Length: 52, dtype: str

In [33]:
all_concerns = set()

for value in products_clean['concern']:
    for concern in value.split(','):
        all_concerns.add(concern.strip())

sorted(all_concerns)

['Acne',
 'Broken barrier',
 'Dark Spots',
 'Exfoliation',
 'Hydration',
 'Irritation',
 'Pigmentation',
 'Pimples',
 'Pores',
 'Skin soothing',
 'Sun protection',
 'Whitehead/Blackhead']

In [34]:
concern_order = [
    'Acne',
    'Pimples',
    'Whitehead/Blackhead',
    'Pores',
    'Pigmentation',
    'Dark Spots',
    'Hydration',
    'Broken barrier',
    'Irritation',
    'Skin soothing',
    'Exfoliation',
    'Sun protection'
]

In [35]:
def standardize_concern(value):
    concerns = [x.strip() for x in value.split(',')]
    concerns = sorted(concerns, key=concern_order.index)
    return ','.join(concerns)

In [36]:
products_clean['concern'] = products_clean['concern'].apply(standardize_concern)

In [37]:
products_clean['concern'].nunique()

39

In [38]:
products_clean['concern'].value_counts()

concern
Sun protection                         28
Hydration                              26
Acne                                   24
Pigmentation                           13
Broken barrier                         12
Hydration,Broken barrier               11
Skin soothing                           9
Pores                                   8
Pigmentation,Dark Spots                 7
Exfoliation                             7
Irritation                              5
Pores,Skin soothing                     5
Whitehead/Blackhead                     4
Pimples                                 4
Acne,Whitehead/Blackhead                4
Dark Spots                              4
Acne,Hydration                          3
Hydration,Irritation                    3
Hydration,Exfoliation                   3
Whitehead/Blackhead,Exfoliation         3
Hydration,Skin soothing                 3
Acne,Dark Spots                         2
Acne,Pimples                            2
Whitehead/Blackhead,Pores               2
Irritation,Skin soothing                2
Acne,Pigmentation                       2
Acne,Pimples,Whitehead/Blackhead        2
Pigmentation,Exfoliation                2
Acne,Pores                              2
Dark Spots,Hydration                    2
Pores,Dark Spots                        2
Hydration,Broken barrier,Irritation     1
Broken barrier,Sun protection           1
Hydration,Sun protection                1
Irritation,Sun protection               1
Pores,Hydration                         1
Whitehead/Blackhead,Broken barrier      1
Pores,Exfoliation                       1
Hydration,Irritation,Skin soothing      1
Name: count, dtype: int64

In [39]:
products_clean['concern'].nunique()

39

In [40]:
products_clean['product'].head(10)

0             Venusia Max Intensive Moisturizing Cream
1                             Saslic Foaming Face Wash
2    The Derma Co 1% Hyaluronic Sunscreen Aqua Ultr...
3                                             Hyalugel
4                              Himalaya Neem Face Wash
5    Mamaearth Ubtan Face Wash with Turmeric & Saff...
6                         Kama Ayurveda Pure Rosewater
7         Simple Kind to Skin Moisturizing Facial Wash
8                                              Emolene
9      Requil Ceramide and Hyaluronic acid moisturizer
Name: product, dtype: str

In [41]:
products_clean['product'].str.strip().head(10)

0             Venusia Max Intensive Moisturizing Cream
1                             Saslic Foaming Face Wash
2    The Derma Co 1% Hyaluronic Sunscreen Aqua Ultr...
3                                             Hyalugel
4                              Himalaya Neem Face Wash
5    Mamaearth Ubtan Face Wash with Turmeric & Saff...
6                         Kama Ayurveda Pure Rosewater
7         Simple Kind to Skin Moisturizing Facial Wash
8                                              Emolene
9      Requil Ceramide and Hyaluronic acid moisturizer
Name: product, dtype: str

In [42]:
products_clean['product'] = products_clean['product'].str.strip()

In [43]:
products_clean.shape

(214, 5)

In [44]:
products_clean.isnull().sum()

skin_type      0
product        0
concern        0
product_url    1
product_pic    0
dtype: int64

In [45]:
products_clean.duplicated().sum()

np.int64(0)

In [46]:
products_clean.dtypes

skin_type      str
product        str
concern        str
product_url    str
product_pic    str
dtype: object

In [47]:
products_clean.to_csv(
    "../data/processed/skinai_products_clean.csv",
    index=False
)

In [48]:
import os

os.path.exists("../data/processed/skinai_products_clean.csv")

True

In [49]:
from sklearn.preprocessing import MultiLabelBinarizer

In [50]:
import pandas as pd

products_clean = pd.read_csv(
    "../data/processed/skinai_products_clean.csv"
)

In [51]:
products_clean.shape

(214, 5)

In [52]:
from sklearn.preprocessing import MultiLabelBinarizer

In [53]:
skin_mlb = MultiLabelBinarizer()

skin_features = skin_mlb.fit_transform(
    products_clean['skin_type'].str.split(',')
)

In [54]:
skin_mlb.classes_

array(['Combination', 'Dry', 'Normal', 'Oily', 'Sensitive'], dtype=object)

In [55]:
skin_features.shape

(214, 5)

In [56]:
skin_features[:5]

array([[0, 1, 0, 0, 0],
       [1, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [57]:
skin_features.shape

(214, 5)

In [58]:
concern_mlb = MultiLabelBinarizer()

concern_features = concern_mlb.fit_transform(
    products_clean['concern'].str.split(',')
)

In [59]:
concern_features.shape

(214, 12)

In [60]:
import numpy as np

product_features = np.hstack([
    skin_features,
    concern_features
])

In [61]:
product_features.shape

(214, 17)

In [62]:
product_features[:5]

array([[0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [63]:
product_features.shape

(214, 17)

In [64]:
user_skin = skin_mlb.transform([['Dry']])

user_concerns = concern_mlb.transform([
    ['Acne', 'Pigmentation']
])

In [65]:
user_features = np.hstack([
    user_skin,
    user_concerns
])

In [66]:
user_features

array([[0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

In [67]:
feature_df = pd.DataFrame(
    product_features,
    columns=list(skin_mlb.classes_) + list(concern_mlb.classes_)
)

In [68]:
feature_df

,Combination,Dry,Normal,Oily,Sensitive,Acne,Broken barrier,Dark Spots,Exfoliation,Hydration,Irritation,Pigmentation,Pimples,Pores,Skin soothing,Sun protection,Whitehead/Blackhead
0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0
1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,1,1,1,1,1,0,0,0,0,0,0,1,0,0,0,0,0
210,1,1,1,1,1,0,0,1,0,0,0,1,0,0,0,0,0
211,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0
212,1,1,1,1,1,0,1,0,0,1,0,0,0,0,0,0,0
213,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0

In [69]:
feature_df.insert(
    0,
    'product',
    products_clean['product'].values
)

In [70]:
feature_df.head()

,product,Combination,Dry,Normal,Oily,Sensitive,Acne,Broken barrier,Dark Spots,Exfoliation,Hydration,Irritation,Pigmentation,Pimples,Pores,Skin soothing,Sun protection,Whitehead/Blackhead
0,Venusia Max Intensive Moisturizing Cream,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0
1,Saslic Foaming Face Wash,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
2,The Derma Co 1% Hyaluronic Sunscreen Aqua Ultr...,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,Hyalugel,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
4,Himalaya Neem Face Wash,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0

In [71]:
feature_df.to_csv(
    "../data/processed/skinai_product_features.csv",
    index=False
)

In [72]:
import os

os.path.exists(
    "../data/processed/skinai_product_features.csv"
)

True

In [73]:
from sklearn.metrics.pairwise import cosine_similarity

In [74]:
similarity_scores = cosine_similarity(
    user_features,
    product_features
)

In [75]:
similarity_scores.shape

(1, 214)

In [76]:
similarity_scores

array([[0.66666667, 0.        , 0.40824829, 0.40824829, 0.        ,
        0.40824829, 0.        , 0.        , 0.40824829, 0.40824829,
        0.40824829, 0.47140452, 0.        , 0.        , 0.43643578,
        0.40824829, 0.        , 0.40824829, 0.40824829, 0.        ,
        0.40824829, 0.40824829, 0.        , 0.40824829, 0.33333333,
        0.        , 0.        , 0.40824829, 0.33333333, 0.23570226,
        0.81649658, 0.51639778, 0.        , 0.        , 0.        ,
        0.25819889, 0.        , 0.33333333, 0.        , 0.33333333,
        0.33333333, 0.        , 0.33333333, 0.33333333, 0.40824829,
        0.40824829, 0.40824829, 0.81649658, 0.25819889, 0.23570226,
        0.57735027, 0.33333333, 0.        , 0.28867513, 0.40824829,
        0.40824829, 0.        , 0.        , 0.51639778, 0.23570226,
        0.40824829, 0.40824829, 0.25819889, 0.        , 0.33333333,
        0.        , 0.23570226, 0.23570226, 0.28867513, 0.28867513,
        0.23570226, 0.40824829, 0.28867513, 0.33333333, 0.23570226,
        0.33333333, 0.23570226, 0.        , 0.40824829, 0.        ,
        0.33333333, 0.43643578, 0.23570226, 0.        , 0.        ,
        0.21821789, 0.        , 0.43643578, 0.47140452, 0.40824829,
        0.47140452, 0.        , 0.40824829, 0.66666667, 0.21821789,
        0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.        ,
        0.40824829, 0.28867513, 0.        , 0.21821789, 0.23570226,
        0.23570226, 0.28867513, 0.        , 0.40824829, 0.81649658,
        0.40824829, 0.40824829, 0.        , 0.23570226, 0.        ,
        0.23570226, 0.        , 0.        , 0.23570226, 0.40824829,
        0.47140452, 0.51639778, 0.33333333, 0.        , 0.43643578,
        0.23570226, 0.25819889, 0.21821789, 0.23570226, 0.40824829,
        0.40824829, 0.23570226, 0.33333333, 0.23570226, 0.47140452,
        0.40824829, 0.43643578, 0.33333333, 0.25819889, 0.25819889,
        0.23570226, 0.33333333, 0.        , 0.57735027, 0.        ,
        0.40824829, 0.        , 0.        , 0.40824829, 0.        ,
        0.21821789, 0.23570226, 0.23570226, 0.28867513, 0.23570226,
        0.21821789, 0.21821789, 0.43643578, 0.        , 0.33333333,
        0.33333333, 0.23570226, 0.28867513, 0.28867513, 0.21821789,
        0.65465367, 0.        , 0.        , 0.40824829, 0.        ,
        0.        , 0.        , 0.        , 0.40824829, 0.40824829,
        0.28867513, 0.51639778, 0.23570226, 0.21821789, 0.25819889,
        0.40824829, 0.23570226, 0.        , 0.23570226, 0.33333333,
        0.        , 0.23570226, 0.51639778, 0.28867513, 0.        ,
        0.43643578, 0.        , 0.28867513, 0.21821789, 0.28867513,
        0.28867513, 0.25819889, 0.        , 0.47140452, 0.28867513,
        0.        , 0.21821789, 0.28867513, 0.47140452, 0.        ,
        0.23570226, 0.23570226, 0.66666667, 0.21821789, 0.47140452,
        0.43643578, 0.23570226, 0.21821789, 0.33333333]])

In [77]:
recommendations = pd.DataFrame({
    'product': products_clean['product'],
    'similarity': similarity_scores[0]
})

In [78]:
recommendations.head()

                                             product  similarity
0           Venusia Max Intensive Moisturizing Cream    0.666667
1                           Saslic Foaming Face Wash    0.000000
2  The Derma Co 1% Hyaluronic Sunscreen Aqua Ultr...    0.408248
3                                           Hyalugel    0.408248
4                            Himalaya Neem Face Wash    0.000000

In [79]:
recommendations = recommendations.sort_values(
    by='similarity',
    ascending=False
)

In [80]:
recommendations.head()

                                             product  similarity
47                Malazia HYDRA VEIL GEL MOISTURIZER    0.816497
30                                    Deriva Cms Gel    0.816497
109  La Pink White Haldi Face Toner with Kakadu Plum    0.816497
0           Venusia Max Intensive Moisturizing Cream    0.666667
93               La Pink White Haldi Ubtan Face Mask    0.666667

In [81]:
top_5 = recommendations.head(5)

In [82]:
top_5

                                             product  similarity
47                Malazia HYDRA VEIL GEL MOISTURIZER    0.816497
30                                    Deriva Cms Gel    0.816497
109  La Pink White Haldi Face Toner with Kakadu Plum    0.816497
0           Venusia Max Intensive Moisturizing Cream    0.666667
93               La Pink White Haldi Ubtan Face Mask    0.666667

In [83]:
def recommend_products(skin_type, concerns, top_k=5):

    user_skin = skin_mlb.transform([[skin_type]])

    user_concerns = concern_mlb.transform([concerns])

    user_features = np.hstack([
        user_skin,
        user_concerns
    ])

    similarity_scores = cosine_similarity(
        user_features,
        product_features
    )[0]

    recommendations = pd.DataFrame({
        'product': products_clean['product'],
        'similarity': similarity_scores
    })

    recommendations = recommendations.sort_values(
        by='similarity',
        ascending=False
    )

    return recommendations.head(top_k)

In [84]:
recommend_products(
    'Dry',
    ['Acne', 'Pigmentation'],
    5
)

                                             product  similarity
47                Malazia HYDRA VEIL GEL MOISTURIZER    0.816497
30                                    Deriva Cms Gel    0.816497
109  La Pink White Haldi Face Toner with Kakadu Plum    0.816497
0           Venusia Max Intensive Moisturizing Cream    0.666667
93               La Pink White Haldi Ubtan Face Mask    0.666667

In [85]:
recommend_products(
    'Oily',
    ['Pores', 'Acne'],
    5
)

                                               product  similarity
163                          Medfoam Foaming Face Wash    0.866025
192        Clensta Red Aloe Vera Oil Control Face Wash    0.866025
61   Green Tea Pore Cleansing Complete Range Combo ...    0.816497
71                    ZitMoist Gel For Acne Prone Skin    0.816497
17                                  Klm Klin Face Wash    0.816497

In [86]:
recommend_products(
    'Sensitive',
    ['Irritation', 'Hydration'],
    5
)

                                          product  similarity
77                    Foxtale Hydrating Face Wash    0.816497
189   Episoft Cleansing Lotion for Sensitive Skin    0.816497
126            Suganda HYDRATING OAT PHA CLEANSER    0.774597
48      Barrier Plus PEPTIDE CERAMIDE MOISTURIZER    0.774597
7    Simple Kind to Skin Moisturizing Facial Wash    0.666667

In [87]:
recommend_products(
    'Combination',
    ['Dark Spots', 'Pigmentation'],
    5
)

                                               product  similarity
69                                   Ethiglo Face Wash    0.866025
27             Dr.Sheth's Liquorice & Lactic Acid Peel    0.816497
31                                   Kojivit Ultra Gel    0.774597
62      The Derma Co 2% Niacinamide Oily Skin Cleanser    0.774597
176  Conscious Chemist Pigmentation & Dark Spot Cor...    0.774597

In [88]:
recommended_products = top_5.merge(
    feature_df,
    on='product'
)

In [89]:
recommended_products.head()

,product,similarity,Combination,Dry,Normal,Oily,Sensitive,Acne,Broken barrier,Dark Spots,Exfoliation,Hydration,Irritation,Pigmentation,Pimples,Pores,Skin soothing,Sun protection,Whitehead/Blackhead
0,Malazia HYDRA VEIL GEL MOISTURIZER,0.816497,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
1,Deriva Cms Gel,0.816497,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
2,La Pink White Haldi Face Toner with Kakadu Plum,0.816497,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,Venusia Max Intensive Moisturizing Cream,0.666667,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0
4,La Pink White Haldi Ubtan Face Mask,0.666667,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0

In [90]:
products_clean[['product', 'skin_type']].head(10)

                                             product         skin_type
0           Venusia Max Intensive Moisturizing Cream               Dry
1                           Saslic Foaming Face Wash  Oily,Combination
2  The Derma Co 1% Hyaluronic Sunscreen Aqua Ultr...               Dry
3                                           Hyalugel               Dry
4                            Himalaya Neem Face Wash            Normal
5  Mamaearth Ubtan Face Wash with Turmeric & Saff...            Normal
6                       Kama Ayurveda Pure Rosewater            Normal
7       Simple Kind to Skin Moisturizing Facial Wash            Normal
8                                            Emolene               Dry
9    Requil Ceramide and Hyaluronic acid moisturizer               Dry

In [ ]:
id="b9t2k5"
eligible_products = products_clean[
    products_clean['skin_type'].str.contains('Dry', case=False, na=False)
].copy()user_concerns = ['Acne', 'Pigmentation']

In [92]:
eligible_indices = eligible_products.index

In [93]:
eligible_features = product_features[eligible_indices]

In [94]:
eligible_features.shape

(125, 17)

In [95]:
filtered_scores = cosine_similarity(
    user_features,
    eligible_features
)[0]

In [96]:
user_concerns = ['Acne', 'Pigmentation']

In [97]:
concern_match_count = eligible_products['concern'].apply(
    lambda x: sum(
        concern in x.split(',')
        for concern in user_concerns
    )
)

In [98]:
concern_match_count.head(10)

0     1
2     0
3     0
8     0
9     0
10    0
11    1
14    1
15    0
18    0
Name: concern, dtype: int64

In [99]:
concern_match_score = concern_match_count / len(user_concerns)

In [100]:
final_scores = (
    0.6 * filtered_scores
    + 0.4 * concern_match_score.values
)

In [101]:
final_scores[:10]

array([0.6       , 0.24494897, 0.24494897, 0.24494897, 0.24494897,
       0.24494897, 0.48284271, 0.46186147, 0.24494897, 0.24494897])

In [102]:
improved_recommendations = eligible_products[
    ['product', 'skin_type', 'concern']
].copy()

In [103]:
improved_recommendations['similarity'] = filtered_scores
improved_recommendations['concern_match'] = concern_match_score.values
improved_recommendations['final_score'] = final_scores

In [104]:
improved_recommendations = improved_recommendations.sort_values(
    by='final_score',
    ascending=False
)

In [105]:
improved_recommendations.head(5)

,product,skin_type,concern,similarity,concern_match,final_score
165,Aziderm Azelaic Acid Gel 10%,"Normal,Dry,Oily,Combination,Sensitive","Acne,Pigmentation",0.654654,1.0,0.792792
47,Malazia HYDRA VEIL GEL MOISTURIZER,Dry,Acne,0.816497,0.5,0.689898
109,La Pink White Haldi Face Toner with Kakadu Plum,Dry,Acne,0.816497,0.5,0.689898
30,Deriva Cms Gel,Dry,Acne,0.816497,0.5,0.689898
0,Venusia Max Intensive Moisturizing Cream,Dry,"Acne,Hydration",0.666667,0.5,0.600000

In [106]:
def get_matched_concerns(product_concerns, user_concerns):
    product_concerns = product_concerns.split(',')

    return [
        concern
        for concern in user_concerns
        if concern in product_concerns
    ]

In [107]:
get_matched_concerns(
    'Acne,Pores,Pigmentation',
    ['Acne', 'Pigmentation']
)

['Acne', 'Pigmentation']

In [108]:
improved_recommendations['matched_concerns'] = (
    improved_recommendations['concern']
    .apply(
        lambda x: get_matched_concerns(
            x,
            user_concerns
        )
    )
)

In [109]:
improved_recommendations[
    ['product', 'concern', 'matched_concerns', 'final_score']
].head(5)

,product,concern,matched_concerns,final_score
165,Aziderm Azelaic Acid Gel 10%,"Acne,Pigmentation","[Acne, Pigmentation]",0.792792
47,Malazia HYDRA VEIL GEL MOISTURIZER,Acne,[Acne],0.689898
109,La Pink White Haldi Face Toner with Kakadu Plum,Acne,[Acne],0.689898
30,Deriva Cms Gel,Acne,[Acne],0.689898
0,Venusia Max Intensive Moisturizing Cream,"Acne,Hydration",[Acne],0.600000

In [110]:
def generate_reasons(skin_type, matched_concerns, user_skin_type):
    reasons = []

    if user_skin_type in skin_type.split(','):
        reasons.append(f"Matches your {user_skin_type} skin type")

    for concern in matched_concerns:
        reasons.append(f"Addresses your {concern} concern")

    return reasons

In [111]:
generate_reasons(
    "Dry,Sensitive",
    ["Acne", "Pigmentation"],
    "Dry"
)

['Matches your Dry skin type',
 'Addresses your Acne concern',
 'Addresses your Pigmentation concern']

In [112]:
improved_recommendations['reasons'] = improved_recommendations.apply(
    lambda row: generate_reasons(
        row['skin_type'],
        row['matched_concerns'],
        'Dry'
    ),
    axis=1
)

In [114]:
improved_recommendations[
    ['product', 'final_score', 'matched_concerns', 'reasons']
].head(5)

,product,final_score,matched_concerns,reasons
165,Aziderm Azelaic Acid Gel 10%,0.792792,"[Acne, Pigmentation]","[Matches your Dry skin type, Addresses your Ac..."
47,Malazia HYDRA VEIL GEL MOISTURIZER,0.689898,[Acne],"[Matches your Dry skin type, Addresses your Ac..."
109,La Pink White Haldi Face Toner with Kakadu Plum,0.689898,[Acne],"[Matches your Dry skin type, Addresses your Ac..."
30,Deriva Cms Gel,0.689898,[Acne],"[Matches your Dry skin type, Addresses your Ac..."
0,Venusia Max Intensive Moisturizing Cream,0.600000,[Acne],"[Matches your Dry skin type, Addresses your Ac..."

In [141]:
def recommend_products_v2(skin_type, concerns, top_k=5):
    valid_concerns = set(concern_mlb.classes_)

    invalid_concerns = [
        concern for concern in concerns
        if concern not in valid_concerns
    ]

    if invalid_concerns:
        raise ValueError(
            f"Invalid concern(s): {invalid_concerns}"
        )

    # 1. Filter products by skin type
    eligible_products = products_clean[
        products_clean['skin_type'].str.contains(
            skin_type,
            case=False,
            na=False
        )
    ].copy()
    if eligible_products.empty:
        return pd.DataFrame(columns=[
        'product',
        'skin_type',
        'concern',
        'similarity',
        'concern_match',
        'final_score',
        'matched_concerns',
        'reasons'
    ])

    # 2. Get feature vectors of eligible products
    eligible_indices = eligible_products.index
    eligible_features = product_features[eligible_indices]

    # 3. Encode the user
    user_skin = skin_mlb.transform([[skin_type]])

    user_concerns = concern_mlb.transform([concerns])

    user_features = np.hstack([
        user_skin,
        user_concerns
    ])

    # 4. Calculate cosine similarity
    similarity_scores = cosine_similarity(
        user_features,
        eligible_features
    )[0]

    # 5. Calculate concern match count
    concern_match_count = eligible_products['concern'].apply(
        lambda x: sum(
            concern in x.split(',')
            for concern in concerns
        )
    )

    # 6. Convert concern matches to a score
    if concerns:
        concern_match_score = concern_match_count / len(concerns)
    else:
        concern_match_score = pd.Series(
        0.0,
        index=eligible_products.index
    )

    # 7. Calculate final score
    final_scores = (
        0.6 * similarity_scores
        + 0.4 * concern_match_score.values
    )

    # 8. Create recommendation DataFrame
    recommendations = eligible_products[
        ['product', 'skin_type', 'concern']
    ].copy()

    recommendations['similarity'] = similarity_scores
    recommendations['concern_match'] = concern_match_score.values
    recommendations['final_score'] = final_scores

    # 9. Find matched concerns
    recommendations['matched_concerns'] = (
        recommendations['concern'].apply(
            lambda x: get_matched_concerns(
                x,
                concerns
            )
        )
    )

    # 10. Generate explanations
    recommendations['reasons'] = recommendations.apply(
        lambda row: generate_reasons(
            row['skin_type'],
            row['matched_concerns'],
            skin_type
        ),
        axis=1
    )

    # 11. Sort by final score
    recommendations = recommendations.sort_values(
        by='final_score',
        ascending=False
    )

    # 12. Return Top-K
    return recommendations.head(top_k)

In [116]:
recommend_products_v2(
    'Dry',
    ['Acne', 'Pigmentation'],
    5
)

,product,skin_type,concern,similarity,concern_match,final_score,matched_concerns,reasons
165,Aziderm Azelaic Acid Gel 10%,"Normal,Dry,Oily,Combination,Sensitive","Acne,Pigmentation",0.654654,1.0,0.792792,"[Acne, Pigmentation]","[Matches your Dry skin type, Addresses your Ac..."
47,Malazia HYDRA VEIL GEL MOISTURIZER,Dry,Acne,0.816497,0.5,0.689898,[Acne],"[Matches your Dry skin type, Addresses your Ac..."
109,La Pink White Haldi Face Toner with Kakadu Plum,Dry,Acne,0.816497,0.5,0.689898,[Acne],"[Matches your Dry skin type, Addresses your Ac..."
30,Deriva Cms Gel,Dry,Acne,0.816497,0.5,0.689898,[Acne],"[Matches your Dry skin type, Addresses your Ac..."
0,Venusia Max Intensive Moisturizing Cream,Dry,"Acne,Hydration",0.666667,0.5,0.600000,[Acne],"[Matches your Dry skin type, Addresses your Ac..."

In [117]:
recommend_products_v2(
    'Oily',
    ['Acne', 'Pores'],
    5
)

,product,skin_type,concern,similarity,concern_match,final_score,matched_concerns,reasons
163,Medfoam Foaming Face Wash,"Oily,Combination","Acne,Pores",0.866025,1.0,0.919615,"[Acne, Pores]","[Matches your Oily skin type, Addresses your A..."
192,Clensta Red Aloe Vera Oil Control Face Wash,"Oily,Combination","Acne,Pores",0.866025,1.0,0.919615,"[Acne, Pores]","[Matches your Oily skin type, Addresses your A..."
17,Klm Klin Face Wash,Oily,Acne,0.816497,0.5,0.689898,[Acne],"[Matches your Oily skin type, Addresses your A..."
108,Tattvalogy Saraswati River Basin Dead Sea Mud ...,Oily,Acne,0.816497,0.5,0.689898,[Acne],"[Matches your Oily skin type, Addresses your A..."
100,Plum Phy Green Tea Face Mask,Oily,Acne,0.816497,0.5,0.689898,[Acne],"[Matches your Oily skin type, Addresses your A..."

In [118]:
recommend_products_v2(
    'Sensitive',
    ['Irritation', 'Hydration'],
    5
)

,product,skin_type,concern,similarity,concern_match,final_score,matched_concerns,reasons
48,Barrier Plus PEPTIDE CERAMIDE MOISTURIZER,"Dry,Sensitive","Hydration,Broken barrier,Irritation",0.774597,1.0,0.864758,"[Irritation, Hydration]","[Matches your Sensitive skin type, Addresses y..."
126,Suganda HYDRATING OAT PHA CLEANSER,"Dry,Combination,Sensitive","Hydration,Irritation",0.774597,1.0,0.864758,"[Irritation, Hydration]","[Matches your Sensitive skin type, Addresses y..."
77,Foxtale Hydrating Face Wash,Sensitive,Hydration,0.816497,0.5,0.689898,[Hydration],"[Matches your Sensitive skin type, Addresses y..."
189,Episoft Cleansing Lotion for Sensitive Skin,Sensitive,Irritation,0.816497,0.5,0.689898,[Irritation],"[Matches your Sensitive skin type, Addresses y..."
91,Kama Aryuveda Sensitive Skin Cleansing Foam,Sensitive,"Irritation,Skin soothing",0.666667,0.5,0.600000,[Irritation],"[Matches your Sensitive skin type, Addresses y..."

In [119]:
recommend_products_v2(
    'Combination',
    ['Dark Spots', 'Pigmentation'],
    5
)

,product,skin_type,concern,similarity,concern_match,final_score,matched_concerns,reasons
69,Ethiglo Face Wash,"Combination,Sensitive","Pigmentation,Dark Spots",0.866025,1.0,0.919615,"[Dark Spots, Pigmentation]","[Matches your Combination skin type, Addresses..."
31,Kojivit Ultra Gel,"Dry,Combination,Sensitive","Pigmentation,Dark Spots",0.774597,1.0,0.864758,"[Dark Spots, Pigmentation]","[Matches your Combination skin type, Addresses..."
62,The Derma Co 2% Niacinamide Oily Skin Cleanser,"Oily,Combination,Sensitive","Pigmentation,Dark Spots",0.774597,1.0,0.864758,"[Dark Spots, Pigmentation]","[Matches your Combination skin type, Addresses..."
176,Conscious Chemist Pigmentation & Dark Spot Cor...,"Normal,Dry,Combination","Pigmentation,Dark Spots",0.774597,1.0,0.864758,"[Dark Spots, Pigmentation]","[Matches your Combination skin type, Addresses..."
124,Fixderma 10% Tranexamic Acid Pigment Correctin...,"Normal,Dry,Oily,Combination,Sensitive","Pigmentation,Dark Spots",0.654654,1.0,0.792792,"[Dark Spots, Pigmentation]","[Matches your Combination skin type, Addresses..."

In [121]:
recommend_products_v2(
    'Dry',
    [],
    5
)

,product,skin_type,concern,similarity,concern_match,final_score,matched_concerns,reasons
0,Venusia Max Intensive Moisturizing Cream,Dry,"Acne,Hydration",0.577350,NaN,NaN,[],[Matches your Dry skin type]
2,The Derma Co 1% Hyaluronic Sunscreen Aqua Ultr...,Dry,Sun protection,0.707107,NaN,NaN,[],[Matches your Dry skin type]
3,Hyalugel,Dry,Hydration,0.707107,NaN,NaN,[],[Matches your Dry skin type]
8,Emolene,Dry,Hydration,0.707107,NaN,NaN,[],[Matches your Dry skin type]
9,Requil Ceramide and Hyaluronic acid moisturizer,Dry,Hydration,0.707107,NaN,NaN,[],[Matches your Dry skin type]

In [128]:
if concerns:
    concern_match_score = concern_match_count / len(concerns)
else:
    concern_match_score = pd.Series(
        0.0,
        index=eligible_products.index
    )

In [129]:
concern_match_score = (
    concern_match_count / len(concerns)
)

In [127]:
skin_type = 'Dry'
concerns = []
top_k = 5

print("Skin type:", skin_type)
print("Concerns:", concerns)
print("Top K:", top_k)

Skin type: Dry
Concerns: []
Top K: 5

In [130]:
if concerns:
    concern_match_score = concern_match_count / len(concerns)
else:
    concern_match_score = pd.Series(
        0.0,
        index=eligible_products.index
    )

print(concern_match_score.head())

0    0.0
2    0.0
3    0.0
8    0.0
9    0.0
dtype: float64

In [132]:
recommend_products_v2(
    'Dry',
    [],
    5
)

,product,skin_type,concern,similarity,concern_match,final_score,matched_concerns,reasons
2,The Derma Co 1% Hyaluronic Sunscreen Aqua Ultr...,Dry,Sun protection,0.707107,0.0,0.424264,[],[Matches your Dry skin type]
8,Emolene,Dry,Hydration,0.707107,0.0,0.424264,[],[Matches your Dry skin type]
3,Hyalugel,Dry,Hydration,0.707107,0.0,0.424264,[],[Matches your Dry skin type]
9,Requil Ceramide and Hyaluronic acid moisturizer,Dry,Hydration,0.707107,0.0,0.424264,[],[Matches your Dry skin type]
10,Simple replenishing rich moisturiser,Dry,Hydration,0.707107,0.0,0.424264,[],[Matches your Dry skin type]

In [133]:
recommend_products_v2(
    'UnknownSkinType',
    ['Acne'],
    5
)

c:\Users\bhuvanasri\OneDrive\Desktop\SahiBhuu\venv\Lib\site-packages\sklearn\preprocessing\_label.py:1016: UserWarning: unknown class(es) ['UnknownSkinType'] will be ignored
  warnings.warn(

ValueError: Found array with 0 sample(s) (shape=(0, 17)) while a minimum of 1 is required by check_pairwise_arrays.

In [137]:
recommend_products_v2(
    'UnknownSkinType',
    ['Acne'],
    5
)

Empty DataFrame
Columns: [product, skin_type, concern, similarity, concern_match, final_score, matched_concerns, reasons]
Index: []

In [138]:
concern_mlb.transform([concerns])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [139]:
recommend_products_v2(
    'Dry',
    ['XYZConcern'],
    5
)

c:\Users\bhuvanasri\OneDrive\Desktop\SahiBhuu\venv\Lib\site-packages\sklearn\preprocessing\_label.py:1016: UserWarning: unknown class(es) ['XYZConcern'] will be ignored
  warnings.warn(

,product,skin_type,concern,similarity,concern_match,final_score,matched_concerns,reasons
2,The Derma Co 1% Hyaluronic Sunscreen Aqua Ultr...,Dry,Sun protection,0.707107,0.0,0.424264,[],[Matches your Dry skin type]
8,Emolene,Dry,Hydration,0.707107,0.0,0.424264,[],[Matches your Dry skin type]
3,Hyalugel,Dry,Hydration,0.707107,0.0,0.424264,[],[Matches your Dry skin type]
9,Requil Ceramide and Hyaluronic acid moisturizer,Dry,Hydration,0.707107,0.0,0.424264,[],[Matches your Dry skin type]
10,Simple replenishing rich moisturiser,Dry,Hydration,0.707107,0.0,0.424264,[],[Matches your Dry skin type]

In [142]:
concerns = ['Acne', 'Pigmentation']

In [144]:
recommend_products_v2(
    'Dry',
    ['Acne', 'XYZConcern'],
    5
)

ValueError: Invalid concern(s): ['XYZConcern']

In [145]:
test_recommendations = recommend_products_v2(
    'Dry',
    ['Acne', 'Pigmentation'],
    5
)

In [146]:
test_recommendations[
    [
        'product',
        'skin_type',
        'concern',
        'similarity',
        'concern_match',
        'final_score',
        'matched_concerns',
        'reasons'
    ]
]

,product,skin_type,concern,similarity,concern_match,final_score,matched_concerns,reasons
165,Aziderm Azelaic Acid Gel 10%,"Normal,Dry,Oily,Combination,Sensitive","Acne,Pigmentation",0.654654,1.0,0.792792,"[Acne, Pigmentation]","[Matches your Dry skin type, Addresses your Ac..."
47,Malazia HYDRA VEIL GEL MOISTURIZER,Dry,Acne,0.816497,0.5,0.689898,[Acne],"[Matches your Dry skin type, Addresses your Ac..."
109,La Pink White Haldi Face Toner with Kakadu Plum,Dry,Acne,0.816497,0.5,0.689898,[Acne],"[Matches your Dry skin type, Addresses your Ac..."
30,Deriva Cms Gel,Dry,Acne,0.816497,0.5,0.689898,[Acne],"[Matches your Dry skin type, Addresses your Ac..."
0,Venusia Max Intensive Moisturizing Cream,Dry,"Acne,Hydration",0.666667,0.5,0.600000,[Acne],"[Matches your Dry skin type, Addresses your Ac..."

In [147]:
test_recommendations_2 = recommend_products_v2(
    'Oily',
    ['Acne', 'Pores'],
    5
)

In [148]:
test_recommendations_2[
    [
        'product',
        'skin_type',
        'concern',
        'similarity',
        'concern_match',
        'final_score',
        'matched_concerns',
        'reasons'
    ]
]

,product,skin_type,concern,similarity,concern_match,final_score,matched_concerns,reasons
163,Medfoam Foaming Face Wash,"Oily,Combination","Acne,Pores",0.866025,1.0,0.919615,"[Acne, Pores]","[Matches your Oily skin type, Addresses your A..."
192,Clensta Red Aloe Vera Oil Control Face Wash,"Oily,Combination","Acne,Pores",0.866025,1.0,0.919615,"[Acne, Pores]","[Matches your Oily skin type, Addresses your A..."
17,Klm Klin Face Wash,Oily,Acne,0.816497,0.5,0.689898,[Acne],"[Matches your Oily skin type, Addresses your A..."
108,Tattvalogy Saraswati River Basin Dead Sea Mud ...,Oily,Acne,0.816497,0.5,0.689898,[Acne],"[Matches your Oily skin type, Addresses your A..."
100,Plum Phy Green Tea Face Mask,Oily,Acne,0.816497,0.5,0.689898,[Acne],"[Matches your Oily skin type, Addresses your A..."